apiVersion: v1
kind: Secret
metadata:
    name: nextjs-secrets
    namespace: tennis-tracker
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:luJ8zicS4qzrDiyHrUR1+RE2lC4ZMxA//2Mn/CJkN9EUrpin69Ut0IhMHRBy4ONa7KAsUVMe4iZQQwWJeuKj2bXR9bWnQrMbcFJrPwzxtXHtKk6zC2KGEmRrta1+eYEi4/+5sxf9ccNfY8JYpC1UPw==,iv:GQcAAC7PhVLYHMeLFCMKeYIhnraZI0x2JUSTP6xzywQ=,tag:X+6eQg3xeupwa42gePkuSw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:n9EXC3CiSgkuKHPTsewkqLfymEfyj8cO53O345T4psDjvlgTmDaogilv,iv:yu1rMSUeTlVOx7H6+xW91vAOcP14lH1JeIw+8Ep1STA=,tag:xjuHhlVzYi8qwVT0Vr7mhw==,type:str]
sops:
    age:
        - recipient: age1swprz6w7uv9wuwk76x397mx7kxmpjkv7f60azaat0l2ht27uvfvq0ngllg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dzdtZk9HcVpiSm1lcC9E
            ZHVYOWEwT2thK2YvQ1pjNnlkMEphOHNEZnlNCjB3RWZ6VTNEcHVpdUY2MGtaV2Fz
            dko2UFQzbmQ2cm9TWktYemk4eDVtRVUKLS0tIC9NYk9pSXdlQU1QQTNGb2JBZDAx
            UzlZTFhrcjRzOGRKMWtxbnRtVmNNNXMK4JCxobTBAhVgpJWqcZH6mvUJjf+QDtZE
            R/YCETfms8AUVa78VvOUuFGoeBQBmeqr2W63JDuf84bpz1d0a4ijNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gj2l69qlla5cctdpxklpcra0nhg4y94j3yws685uylhwmvfmv3rq0mxryr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MkU3clI3dHdrRVp0K1JU
            ZGVEVkpzMCsvaFZmb3N0c3JvSmtnTHN1Z0hRCmZ4UkFDRmNQcnh4MFVhWmVqVHl2
            NGdkOXJQRHpyamRmbndmMlp5UHVadGcKLS0tIFNyK0VwUFVOZ3Q0dGF0M3lmdmN3
            dVR3ZnRxbTJLa1NaeGVxUDhGbFFmZlEKxIKOk0ZFDjVZinlGNsKQF6/o9Q3dZqo4
            gzUcoQ+m5FC2v+lKfzAKVeF5fNlafmiUJEmeBF/uQ1Yf+79quNQ6hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T14:07:26Z"
    mac: ENC[AES256_GCM,data:X0ez08vVTtuFqbX3HlaGjJCS8UD7Lq2VsL5+Co9Q3uFCNWWAto5b2WaBtBd3Ejhgu6yNA1xj0hujPlak46u12bwOCmSjerlZ5hmAAdebq4dw2tC0W3SGbVJdKf2iMHaO/aww8CDhWVWQPbaKYqQO6wHXWD/k8BI026k2y3uNuDQ=,iv:i4OnCbQMWFSeoBD8hLJ2Mc3RG5EEKQ+k1xixDF/Tq9c=,tag:ZuFcDljlE3gI1+u5E2mLWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
