apiVersion: v1
kind: Secret
metadata:
  name: nextjs-secrets
  namespace: tennis-tracker
type: Opaque
stringData:
  DATABASE_URL: "postgresql://tennis_tracker:CHANGE_ME@pgpool.cnpg.svc.cluster.local:5432/tennis_tracker"
  JWT_SECRET: "CHANGE_ME_GENERATE_RANDOM_STRING"
