apiVersion: v1
kind: Secret
metadata:
    name: nextjs-secrets
    namespace: tennis-tracker
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:9wngZ1kXQUFObr8n5romCKIgdEmGH57TJLfI4v4sPo/F0gviLVrQdfX9mXbotXk+BbXub4W1bhwd4ZwYzprm4t5OhbEo67Eiq3pkn4AEldNKhmu5hoJ2A3Sd1ybCAEqt10qV638DiDED2tYqM00GIw==,iv:j1RRcG8VSJRU8HbePlAcWOZk6uyUa7PtdxtIlHhpQp0=,tag:4gK3gvphP+qIRKPO35meTQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:jAJOxNHKlE2VhV09DpQtx0Us4R0VdacyWsVRpn+8bZLe8jOybBzyNYEG,iv:ciChjDWn38bVd6KCZaQ9dRl4yBEd2C+1iGM46pscAOM=,tag:AEHS3H67aiW79dqzt6a17g==,type:str]
sops:
    age:
        - recipient: age1ent890jluz4024en5v8kx5kttvjx2vgecmzfg9wjndyvuwhr39hqsdt35z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFalE0Tnl3Ty9Mdk85Z2ZU
            SFFMZzY1WnUzZHBObGdOTVJjWEd4Zm5adnpNClV1Z2lybktmdkFaTUpWY2o0TkM1
            b1N3Vnh1WjU3OTlyVFZHcE16dktySWcKLS0tIEU4Z1ljc25xVWRLVWl6aVhIZGM5
            VGJZNHc3SEtjekdtWUk4VDRobGo1VXMKZ0gOLmU4WxqB2VjoTe5Vf9jVOckbmCk0
            trqXYmPZs1+/YG1NBviLsEomOW5Gc0K7M3PUweO6ZqOLscV5Qtm8cw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gj2l69qlla5cctdpxklpcra0nhg4y94j3yws685uylhwmvfmv3rq0mxryr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVXpTZFcvSXVtZ3hTc3Bl
            UzEvQ0Y0dGxwVFhISDF0Vi9iOGhkb0hWcmljCng5ZEpHMnZlcTQ2QkwxRWN4UkpT
            dEFrOVNUVVlpdzVvSi8ra3BWSGthbkEKLS0tIGlpbmtkc2EyeWl4QjFxbGNIajlS
            VHRWZjY3ZnppVXRJRGwzTmM3Rk5tUmcKZnx9sHSozSLY0Mi4DN+BZCYVoyrrAjMI
            CNrajaTWel4OjPueHiLke/obI9Qlyi8mW9T2uYV50LoVlKz2SypUjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T14:07:38Z"
    mac: ENC[AES256_GCM,data:B3fasoZ+00q+5KxTBhxiqSH4oZ2UK7JOasDpFJ5r8Pc7cBJMXpB0itKvyEpSQlpyGeX7omHHUXlFNqwB+FbOPQwGulFhCrRtQcdtIM7PRVYABD/DxQW5Nm4rULc6CRofR/pbVXWqxS4fknsktEoiPA7F9WH44u7YBtR/Duc8GKA=,iv:syD2t0kwh8tNOCNP0WfGt36R5AC70/9kakuUAZMRhuY=,tag:oRh9uD6hSCBOYRvlh15SKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
